### ISSUE TITLE
Unable to install and use on a clean app

### ISSUE THREAD

**Issue by nfacha** [rajivshah3/react-native-google-safetynet#41]
After installing and linking the module on a clean react-native init app and importing into a component it won't work, there are missing dependencies that are not installed by npm, try to install and use this module into a clean app to reproduce the issue.

```
error: bundling failed: Error: Unable to resolve module stream from /home/facha/freemcserver/test/node_modules/jws/lib/sign-stream.js: Module stream does not exist in the Haste module map

(/home/facha/freemcserver/test/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:209:1301)
    at ResolutionRequest.resolveDependency (/home/facha/freemcserver/test/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:83:16)
    at DependencyGraph.resolveDependency (/home/facha/freemcserver/test/node_modules/metro/src/node-haste/DependencyGraph.js:238:485)
    at Object.resolve (/home/facha/freemcserver/test/node_modules/metro/src/lib/transformHelpers.js:180:25)
    at dependencies.map.result (/home/facha/freemcserver/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:311:29)
    at Array.map (<anonymous>)
    at resolveDependencies (/home/facha/freemcserver/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:307:16)
    at /home/facha/freemcserver/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:164:33
    at Generator.next (<anonymous>)
    at step (/home/facha/freemcserver/test/node_modules/metro/src/DeltaBundler/traverseDependencies.js:266:307)
```

Versions:
```"dependencies": {
    "react": "16.5.0",
    "react-native": "0.57.0",
    "react-native-google-safetynet": "^0.2.3"

**Comment by rajivshah3** [comment]
Hmm. I might not have run into this issue with 
https://github.com/iotaledger/trinity-wallet since we already used 
https://github.com/tradle/rn-nodeify to patch node core modules (stream is a core node module but React Native doesn’t recognize it). If you want to fix this now you could try adding that package as a postinstall hook. I’ll make sure to fix this in the next few days
